[project]
name = "tms"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "accelerate>=1.12.0",
    "cap-ml @ git+https://github.com/lorenzovolpi/cap-ml.git",
    "datasets>=4.5.0",
    "fastparquet>=2025.12.0",
    "numba>=0.63.1",
    "numpy<2.4.0",
    "pandatex @ git+https://github.com/lorenzovolpi/pandatex.git",
    "protobuf>=6.33.5",
    "pyarrow>=23.0.0",
    "sentencepiece>=0.2.1",
    "tiktoken>=0.12.0",
    "torchvision>=0.25.0",
    "transformers[torch]>=5.0.0",
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 120

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

